import { Product } from "@/lib/types";

export const ALL_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Ikan Tuna Sirip Kuning Segar (Yellowfin Tuna)",
        price: 85000,
        originalPrice: 95000,
        image: "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller1", name: "Nelayan Cilacap Jaya", location: "Cilacap, Jawa Tengah", type: "Nelayan" },
        rating: 4.8,
        sold: 120,
        stock: 50,
        category: "Hasil Laut",
        isFresh: true,
        harvestTime: "Tangkap dini hari tadi",
    },
    {
        id: "2",
        name: "Udang Vaname Premium Size 30",
        price: 110000,
        image: "https://images.unsplash.com/photo-1565680018446-7e8ee99eb654?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller2", name: "Tambak Udang Banyuwangi", location: "Banyuwangi, Jawa Timur", type: "Peternak" },
        rating: 4.9,
        sold: 450,
        stock: 50,
        category: "Hasil Laut",
        isFresh: true,
    },
    {
        id: "3",
        name: "Sayur Bayam Organik Hidroponik",
        price: 15000,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller3", name: "Kebun Hijau Lembang", location: "Bandung, Jawa Barat", type: "Petani" },
        rating: 4.7,
        sold: 80,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Panen pagi ini",
    },
    {
        id: "4",
        name: "Daging Sapi Slice Low Fat 500gr",
        price: 75000,
        image: "https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller4", name: "Peternakan Sapi Boyolali", location: "Boyolali, Jawa Tengah", type: "Peternak" },
        rating: 4.6,
        sold: 210,
        stock: 50,
        category: "Daging",
        isFresh: true,
    },
    {
        id: "5",
        name: "Cumi-Cumi Segar Ukuran Sedang",
        price: 65000,
        originalPrice: 70000,
        image: "https://images.unsplash.com/photo-1606850780554-b55ea25db2bd?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller5", name: "Nelayan Pantura", location: "Cirebon, Jawa Barat", type: "Nelayan" },
        rating: 4.5,
        sold: 85,
        stock: 50,
        category: "Hasil Laut",
        isFresh: true,
    },
    {
        id: "6",
        name: "Kerupuk Ikan Tenggiri Asli",
        price: 25000,
        image: "https://images.unsplash.com/photo-1626202269926-2a8187ae2765?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller6", name: "Oleh-Oleh Khas Tuban", location: "Tuban, Jawa Timur", type: "UMKM" },
        rating: 4.8,
        sold: 1000,
        stock: 50,
        category: "Olahan",
    },
    {
        id: "7",
        name: "Kepiting Bakau Hidup (Live Mud Crab)",
        price: 180000,
        image: "https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller7", name: "Nelayan Mangrove", location: "Balikpapan, Kalimantan Timur", type: "Nelayan" },
        rating: 5.0,
        sold: 40,
        stock: 50,
        category: "Hasil Laut",
        isFresh: true,
    },
    {
        id: "8",
        name: "Tomat Cherry Merah Manis 500gr",
        price: 22000,
        image: "https://images.unsplash.com/photo-1524593166156-311f36f2b697?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller8", name: "Petani Modern Batu", location: "Batu, Jawa Timur", type: "Petani" },
        rating: 4.7,
        sold: 150,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Kemarin sore",
    },
    {
        id: "9",
        name: "Cabai Rawit Merah Super Pedas 1kg",
        price: 45000,
        originalPrice: 55000,
        image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller9", name: "Petani Cabai Brebes", location: "Brebes, Jawa Tengah", type: "Petani" },
        rating: 4.9,
        sold: 620,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Panen pagi ini",
    },
    {
        id: "10",
        name: "Bawang Merah Brebes Grade A 1kg",
        price: 35000,
        image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller10", name: "Tani Bawang Sejahtera", location: "Brebes, Jawa Tengah", type: "Petani" },
        rating: 4.8,
        sold: 890,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
    {
        id: "11",
        name: "Bawang Putih Lokal Segar 500gr",
        price: 28000,
        image: "https://images.unsplash.com/photo-1615477992925-ba6244cb05c8?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller11", name: "Petani Dieng Wonosobo", location: "Wonosobo, Jawa Tengah", type: "Petani" },
        rating: 4.6,
        sold: 340,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
    {
        id: "12",
        name: "Wortel Organik Segar Dieng 1kg",
        price: 18000,
        image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller12", name: "Kebun Organik Dieng", location: "Wonosobo, Jawa Tengah", type: "Petani" },
        rating: 4.7,
        sold: 230,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Panen kemarin",
    },
    {
        id: "13",
        name: "Kangkung Segar Ikatan Besar",
        price: 5000,
        image: "https://images.unsplash.com/photo-1627885465912-326af59e7e7a?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller13", name: "Petani Sayur Karawang", location: "Karawang, Jawa Barat", type: "Petani" },
        rating: 4.5,
        sold: 1200,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Cabut pagi ini",
    },
    {
        id: "14",
        name: "Terong Ungu Segar 1kg",
        price: 12000,
        image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller14", name: "Tani Makmur Subang", location: "Subang, Jawa Barat", type: "Petani" },
        rating: 4.4,
        sold: 95,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
    {
        id: "15",
        name: "Mangga Harum Manis Probolinggo 1kg",
        price: 30000,
        originalPrice: 38000,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller15", name: "Kebun Mangga Probolinggo", location: "Probolinggo, Jawa Timur", type: "Petani" },
        rating: 4.9,
        sold: 520,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Petik kemarin sore",
    },
    {
        id: "16",
        name: "Jeruk Keprok Batu Manis 1kg",
        price: 25000,
        image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller16", name: "Petani Jeruk Batu", location: "Batu, Jawa Timur", type: "Petani" },
        rating: 4.8,
        sold: 410,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
    {
        id: "17",
        name: "Jahe Merah Emprit Segar 500gr",
        price: 32000,
        image: "https://images.unsplash.com/photo-1635848520330-802c38d4c995?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller17", name: "Petani Rempah Boyolali", location: "Boyolali, Jawa Tengah", type: "Petani" },
        rating: 4.7,
        sold: 180,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
    {
        id: "18",
        name: "Kentang Dieng Premium 1kg",
        price: 20000,
        image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller18", name: "Petani Kentang Dataran Tinggi", location: "Banjarnegara, Jawa Tengah", type: "Petani" },
        rating: 4.8,
        sold: 560,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Panen 2 hari lalu",
    },
    {
        id: "19",
        name: "Jagung Manis Pipilan 1kg",
        price: 15000,
        image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller19", name: "Tani Jagung Malang", location: "Malang, Jawa Timur", type: "Petani" },
        rating: 4.6,
        sold: 320,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
        harvestTime: "Panen pagi ini",
    },
    {
        id: "20",
        name: "Alpukat Mentega Jumbo (/buah)",
        price: 15000,
        image: "https://images.unsplash.com/photo-1523049673856-382a62v97529q?auto=format&fit=crop&q=80&w=800",
        seller: { id: "seller20", name: "Kebun Alpukat Garut", location: "Garut, Jawa Barat", type: "Petani" },
        rating: 4.9,
        sold: 270,
        stock: 50,
        category: "Sayur & Buah",
        isFresh: true,
    },
];
